Update master
Field-Robotics-Japan/UnitySensors pull request #60
Opened 2023-08-09 09:59 UTC by Autumn60

2023-11-08 07:22 UTC, RyodoTanaka commented on Assets/UnitySensors/Runtime/Scripts/Sensors/IMU/IMUSensor.cs
This Update does not contain noise model.
I will merge this in this case.
But  we need to add them ASAP, at least gaussian noise.

2023-11-08 07:27 UTC, RyodoTanaka requested changes
TF Sensor sample scene is needed to merge.

Also, in the near future, we need to add noise model for following sensors.
- GPS
- IMU

But those noise model is not necessary for this merge.
What we need is only add TF sensor's sample scene.

2023-11-08 07:27 UTC, RyodoTanaka commented on Assets/UnitySensors/Runtime/Scripts/Sensors/TF/TFSensor.cs
The TF Sensor Sample is not added.
After adding them, I will merge it.

2023-11-08 07:27 UTC, RyodoTanaka commented on Assets/UnitySensorsROS/Editor/URDF2TFConverter/URDF2TFConverter.cs
The sample scene and sample URDF is needed, I think.
But this is not the main sensors. Thus, if there are not, I will merge it.

2023-12-03 09:39 UTC, Autumn60 commented on Assets/UnitySensors/Runtime/Scripts/Sensors/TF/TFSensor.cs
[TF is ROS onlyhttps://github.com/Field-Robotics-Japan/UnitySensors/pull/72](https://github.com/Field-Robotics-Japan/UnitySensors/pull/72)

Since TF is one of the features that ROS has, I think the sample scene should only be implemented in UnitySensorsROS.

TFはROSの機能なので、UnitySensors側ではなくUnitySensorsROS側にのみサンプルシーンを置くべきだと考えています。
TFSensor.csがUnitySensors内に配置されているのは、ディレクトリ構成を統一するためです。

2023-12-03 09:51 UTC, Autumn60 commented on Assets/UnitySensors/Runtime/Scripts/Sensors/IMU/IMUSensor.cs
For Livox and Velodyne, GaussianNoise is already implemented.
Currently, the GaussianNoise class is not implemented because the noise generation process is implemented within parallel and GPU processing.

LivoxとVelodyneについてはガウシアンノイズは実装済みです。
これらのノイズ生成処理は並列処理などの内部に実装されているため、GaussianNoiseクラス自体はまだありません。

2023-12-04 18:27 UTC, RyodoTanaka reviewed
Checked latest master modification.

2023-12-04 18:28 UTC, RyodoTanaka commented on Assets/UnitySensors/Runtime/Scripts/Sensors/TF/TFSensor.cs
TFの機能を分離したPRをマージしました。
方針についても理解しました。本件はこれで問題ないのでマージします！！

2023-12-04 18:58 UTC, RyodoTanaka commented on Assets/UnitySensors/Runtime/Scripts/Sensors/IMU/IMUSensor.cs
I did not word this point well enough. Sorry about that. I thought the noise was necessary for GPS and IMU. We also confirmed that Livox and Velodyne are implemented without any problems.

Regarding the noise of GPS and IMU, I would like to merge them for the following reasons and set them as future issues. 1.

1) GPS Noise We think it is necessary to change not only GussianNoise but also its variance and outlier setting depending on the FIX situation. Therefore, we would like to set this as an issue for future implementation. We would like to implement it after setting up the noise model. 2. We need to discuss whether or not drift noise should be implemented for IMU noise as well. We believe that it is necessary to deliberate whether drift noise should be implemented for IMU noise as well.

Since the commit contents of this PR are larger than the above concerns, we would like to prioritize to merge them first. I will raise an Issue regarding the concerns.

ノイズモデルについて言葉足らずでした。申し訳ありません。上記のReview時点では、GPSとIMUにノイズが必要だとと考えていました。また、LivoxとVelodyneについても問題なく実装されていることを確認しました。

GPSとIMUのノイズの実装については、以下の理由から本PRでは一旦無視し、今後の課題としたいと思います。1.

1. GPSノイズ 
  GussianNoiseだけでなく、分散や外れ値の設定もGPSのFIXの状況に応じて変更する必要があると考えています。そのため、今後の課題として設定し、どこまでノイズモデルを設定するか決定してから実装したいと考えます。
2. IMUノイズ
  ドリフトノイズを実装すべきかどうか議論する必要があると考えます。こちらについてもどこまでノイズモデルを設定するか決定してから実装したいと考えます。

本PRのコミット内容は上記の懸念事項よりも大きいため、優先順位をつけて先にマージしたいと思います。懸念事項についてはIssueを立てておきます。

2023-12-04 18:59 UTC, RyodoTanaka approved these changes
I approve this PR.
The discussion is already written in each commits.

2023-12-04 19:00 UTC, merged

2023-12-04 19:08 UTC, RyodoTanaka commented on Assets/UnitySensors/Runtime/Scripts/Sensors/IMU/IMUSensor.cs
Linked to #73 #74 for GPS and IMU noise models.